name: 'Release Cliq'
description: 'Convert to a Cliq slides template'
inputs:
  webhook:
    description: Webhook URL.
    required: true
  token:
    description: Zoho Cliq zapikey or user webhook token.
    required: true
  sender-name:
    description: Custom sender name for the message.
    required: false
  sender-image:
    description: Custom sender profile picture.
    required: false
  title:
    description: Title of the message.
    required: false
  text:
    description: Body of the message.
    required: false
  message-commit:
    description: 'Message Commit'
    required: true
outputs:
  message-json: 
    description: 'JSON format of the message sent.'
runs:
  using: 'node16'
  main: 'dist/index.js'